/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package red;

import javax.swing.JOptionPane;

/**
 *
 * @author damas
 */
public class tAvaliação extends javax.swing.JFrame {

    /**
     * Creates new form tAvaliação
     */
    public tAvaliação() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgGrauSatisfação = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblGrau = new javax.swing.JLabel();
        lblAD = new javax.swing.JLabel();
        rbTI = new javax.swing.JRadioButton();
        rbI = new javax.swing.JRadioButton();
        rbInD = new javax.swing.JRadioButton();
        rbS = new javax.swing.JRadioButton();
        rbMS = new javax.swing.JRadioButton();
        lblFeed = new javax.swing.JLabel();
        lblBah = new javax.swing.JLabel();
        List = new javax.swing.JScrollPane();
        ListX = new javax.swing.JTextArea();
        lblFeedback = new javax.swing.JLabel();
        lblK = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        Envio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblBye = new javax.swing.JLabel();
        lblHelados = new javax.swing.JLabel();
        lblCute = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblGrau.setFont(new java.awt.Font("Linux Libertine G", 3, 15)); // NOI18N
        lblGrau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrau.setText("Qual é o seu grau de satisfação com o uso de nossa plataforma? ");

        lblAD.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        lblAD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAD.setText("Avaliação de desempenho");

        rbTI.setBackground(new java.awt.Color(255, 255, 255));
        rbgGrauSatisfação.add(rbTI);
        rbTI.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        rbTI.setText("Totalmente insatisfeita(o) ");
        rbTI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTIActionPerformed(evt);
            }
        });

        rbI.setBackground(new java.awt.Color(255, 255, 255));
        rbgGrauSatisfação.add(rbI);
        rbI.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        rbI.setText("Insatisfeito(a)");
        rbI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIActionPerformed(evt);
            }
        });

        rbInD.setBackground(new java.awt.Color(255, 255, 255));
        rbgGrauSatisfação.add(rbInD);
        rbInD.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        rbInD.setText("Indiferente");
        rbInD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbS.setBackground(new java.awt.Color(255, 255, 255));
        rbgGrauSatisfação.add(rbS);
        rbS.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        rbS.setText("Satisfeita(o)");
        rbS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbMS.setBackground(new java.awt.Color(255, 255, 255));
        rbgGrauSatisfação.add(rbMS);
        rbMS.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        rbMS.setText("Muito satisfeito(a)");
        rbMS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMSActionPerformed(evt);
            }
        });

        lblFeed.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        lblFeed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFeed.setText("  Pedimos que nos dê seu feedback em relação ao uso da plataforma.");

        lblBah.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        lblBah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBah.setText("  O que pode ser melhorado, do que você sentiu falta... ");

        ListX.setColumns(20);
        ListX.setRows(5);
        List.setViewportView(ListX);

        lblFeedback.setFont(new java.awt.Font("Book Antiqua", 3, 16)); // NOI18N
        lblFeedback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeedback.setText("Se possível, conte nos sobre o uso de nosso aplicativo!");

        lblK.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        lblK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblK.setText("  Conte-nos sobre sua experiência no campo abaixo!");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red/sorvetepc.png"))); // NOI18N

        Envio.setFont(new java.awt.Font("Book Antiqua", 3, 16)); // NOI18N
        Envio.setText("Enviar resposta");
        Envio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblGrau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbTI, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbInD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(94, 94, 94))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48)))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Envio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(List))))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(lblFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGrau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbInD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(lblFeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(lblK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(List)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Envio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel3.setBackground(new java.awt.Color(176, 217, 178));

        lblBye.setBackground(new java.awt.Color(51, 255, 204));
        lblBye.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        lblBye.setForeground(new java.awt.Color(69, 180, 137));
        lblBye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBye.setText("Agradecemos pela preferência, um belo dia para você!");

        lblHelados.setFont(new java.awt.Font("Book Antiqua", 3, 36)); // NOI18N
        lblHelados.setForeground(new java.awt.Color(69, 180, 137));
        lblHelados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelados.setText("Helados Ice Cream");

        lblCute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red/Mint.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBye, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addComponent(lblHelados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHelados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblCute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(lblBye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTIActionPerformed

    private void rbMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMSActionPerformed

    private void EnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvioActionPerformed
        JOptionPane.showConfirmDialog(null, "Muito agradecidos por sua resposta!", "Feedback enviado", JOptionPane.DEFAULT_OPTION);
        dispose();
    }//GEN-LAST:event_EnvioActionPerformed

    private void rbIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tAvaliação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tAvaliação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tAvaliação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tAvaliação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tAvaliação().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Envio;
    private javax.swing.JScrollPane List;
    private javax.swing.JTextArea ListX;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAD;
    private javax.swing.JLabel lblBah;
    private javax.swing.JLabel lblBye;
    private javax.swing.JLabel lblCute;
    private javax.swing.JLabel lblFeed;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblGrau;
    private javax.swing.JLabel lblHelados;
    private javax.swing.JLabel lblK;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JRadioButton rbI;
    private javax.swing.JRadioButton rbInD;
    private javax.swing.JRadioButton rbMS;
    private javax.swing.JRadioButton rbS;
    private javax.swing.JRadioButton rbTI;
    private javax.swing.ButtonGroup rbgGrauSatisfação;
    // End of variables declaration//GEN-END:variables
}
