/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package red;

/**
 *
 * @author damas
 */
public class tProdutos extends javax.swing.JFrame {

    /**
     * Creates new form tProdutos
     */
    public tProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Llogo = new javax.swing.JLabel();
        Introdução = new javax.swing.JLabel();
        Atualmente = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        Pistache = new javax.swing.JLabel();
        Napolitano = new javax.swing.JLabel();
        Abacaxi = new javax.swing.JLabel();
        Açai = new javax.swing.JLabel();
        Azul = new javax.swing.JLabel();
        Menta = new javax.swing.JLabel();
        Morango = new javax.swing.JLabel();
        Ovomaltine = new javax.swing.JLabel();
        Sabores = new javax.swing.JComboBox<>();
        SaborN = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Icone = new javax.swing.JLabel();
        Helados = new javax.swing.JLabel();
        Frase1 = new javax.swing.JLabel();
        Frase2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Llogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Llogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sorvetepc.png"))); // NOI18N

        Introdução.setFont(new java.awt.Font("Linux Libertine G", 3, 16)); // NOI18N
        Introdução.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Introdução.setText("Olá, seja bem-vinda(o) à página dedicada ao manuseio de produtos. ");

        Atualmente.setFont(new java.awt.Font("Linux Libertine G", 3, 16)); // NOI18N
        Atualmente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Atualmente.setText("Atualmente os sabores de sorvete disponíveis para os clientes são:");

        lblF.setFont(new java.awt.Font("Linux Libertine G", 3, 16)); // NOI18N
        lblF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblF.setText("Faça uma sugestão! Qual sabor deveria ser adicionado e/ou excluído? ");

        Pistache.setBackground(new java.awt.Color(0, 0, 0));
        Pistache.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Pistache.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cmon'.jpg"))); // NOI18N
        Pistache.setText("Pistache");

        Napolitano.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Napolitano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Napolitano.jpg"))); // NOI18N
        Napolitano.setText("Napolitano");

        Abacaxi.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Abacaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AB.jpg"))); // NOI18N
        Abacaxi.setText("Abacaxi + Buriti ");

        Açai.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Açai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Açai.jpg"))); // NOI18N
        Açai.setText("Açaí");

        Azul.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Caneta Azul.jpg"))); // NOI18N
        Azul.setText("Céu azul");

        Menta.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Menta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menta e choco.jpg"))); // NOI18N
        Menta.setText("Menta e chocolate");

        Morango.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Morango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MorangoCaminhão.jpg"))); // NOI18N
        Morango.setText("Morango");

        Ovomaltine.setFont(new java.awt.Font("Linux Libertine G", 2, 14)); // NOI18N
        Ovomaltine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ovomaltine.jpg"))); // NOI18N
        Ovomaltine.setText("Ovomaltine");

        Sabores.setFont(new java.awt.Font("Linux Libertine G", 2, 16)); // NOI18N
        Sabores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abacaxi e Buriti ", "Açaí", "Céu azul", "Menta e chocolate", "Morango", "Napolitano", "Ovomaltine", "Pistache" }));

        SaborN.setFont(new java.awt.Font("Linux Libertine G", 3, 12)); // NOI18N
        SaborN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaborNActionPerformed(evt);
            }
        });

        Add.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        Add.setText("Adicionar");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Remover.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Linux Libertine G", 3, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Llogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Introdução, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Atualmente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Sabores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Menta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Abacaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Açai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(220, 220, 220))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Azul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ovomaltine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Napolitano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Morango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pistache, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(Remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(SaborN)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Llogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(Introdução, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Atualmente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Abacaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Morango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Açai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Napolitano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Azul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ovomaltine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Menta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pistache, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Sabores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaborN)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel2.setBackground(new java.awt.Color(222, 195, 242));

        Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ice-cream-cup.png"))); // NOI18N

        Helados.setFont(new java.awt.Font("Book Antiqua", 3, 36)); // NOI18N
        Helados.setForeground(new java.awt.Color(153, 0, 153));
        Helados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Helados.setText("Helados Ice Cream");

        Frase1.setFont(new java.awt.Font("Book Antiqua", 3, 16)); // NOI18N
        Frase1.setForeground(new java.awt.Color(153, 0, 153));
        Frase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frase1.setText("\"CUIDADO, pois se esperar a comida esfriar demais... outro vem e come!\"");

        Frase2.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        Frase2.setForeground(new java.awt.Color(153, 0, 153));
        Frase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frase2.setText(" Agno Pereira de Alencar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Helados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Icone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Frase1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addComponent(Frase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Helados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(Icone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(Frase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaborNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaborNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaborNActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        String novoSabor = SaborN.getText();
        Sabores.addItem(novoSabor);
    }//GEN-LAST:event_AddActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
       Sabores.removeItem(Sabores.getSelectedItem());
    }//GEN-LAST:event_RemoverActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        tPrincipal back = new tPrincipal();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abacaxi;
    private javax.swing.JButton Add;
    private javax.swing.JLabel Atualmente;
    private javax.swing.JLabel Azul;
    private javax.swing.JLabel Açai;
    private javax.swing.JLabel Frase1;
    private javax.swing.JLabel Frase2;
    private javax.swing.JLabel Helados;
    private javax.swing.JLabel Icone;
    private javax.swing.JLabel Introdução;
    private javax.swing.JLabel Llogo;
    private javax.swing.JLabel Menta;
    private javax.swing.JLabel Morango;
    private javax.swing.JLabel Napolitano;
    private javax.swing.JLabel Ovomaltine;
    private javax.swing.JLabel Pistache;
    private javax.swing.JButton Remover;
    private javax.swing.JTextField SaborN;
    private javax.swing.JComboBox<String> Sabores;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblF;
    // End of variables declaration//GEN-END:variables
}
